# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='hours',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
