# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0003_auto_20160202_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
