# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munch', '0007_auto_20160317_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
